version: "3.7"
services:
  users-api:
    build:
      context: .
      dockerfile: users-api/Dockerfile
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: ${DB_PASSWORD:-dMVZFeBWLOzYRV71} #It is strongly recommended to provide DB_PASSWORD in the environment rather than use this default.
      LOAD_DATA: ${LOAD_DATA:-False} # Will not load the test data by default, instead it will use the db-snapshot
    ports:
      - 8000:8000
    depends_on:
      - db

  users-ui:
    build:
      context: .
      dockerfile: users-ui/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - users-api

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dMVZFeBWLOzYRV71}
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: /db-snapshots
        target: /docker-entrypoint-initdb.d

